name: tinygptv
channels:
  - defaults
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - accelerate==0.20.3
    - aiofiles==23.2.1
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - altair==5.2.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - appdirs==1.4.4
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - bitsandbytes==0.37.0
    - braceexpand==0.1.7
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cmake==3.28.1
    - comm==0.2.0
    - contourpy==1.2.0
    - cycler==0.12.1
    - datasets==2.15.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - decord==0.6.0
    - dill==0.3.7
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - exceptiongroup==1.2.0
    - executing==2.0.1
    - fastapi==0.105.0
    - ffmpy==0.3.1
    - filelock==3.13.1
    - fonttools==4.46.0
    - frozenlist==1.4.1
    - fsspec==2023.10.0
    - gitdb==4.0.11
    - gitpython==3.1.40
    - gradio==3.47.1
    - gradio-client==0.6.0
    - h11==0.14.0
    - httpcore==1.0.2
    - httpx==0.25.2
    - huggingface-hub==0.19.4
    - idna==3.6
    - imageio==2.33.1
    - importlib-metadata==7.0.0
    - importlib-resources==6.1.1
    - iopath==0.1.10
    - ipykernel==6.27.1
    - ipython==8.18.1
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - jupyter-client==8.6.0
    - jupyter-core==5.5.1
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - lit==17.0.6
    - markupsafe==2.1.3
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.6
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - nest-asyncio==1.5.8
    - networkx==3.2.1
    - nltk==3.8.1
    - numpy==1.26.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - orjson==3.9.10
    - packaging==23.2
    - pandas==2.1.4
    - parso==0.8.3
    - peft==0.2.0
    - pexpect==4.9.0
    - pillow==10.1.0
    - platformdirs==4.1.0
    - portalocker==2.8.2
    - progressbar2==4.3.0
    - prompt-toolkit==3.0.43
    - protobuf==4.25.1
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==14.0.2
    - pyarrow-hotfix==0.6
    - pydantic==2.5.2
    - pydantic-core==2.14.5
    - pydub==0.25.1
    - pygments==2.17.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-multipart==0.0.6
    - python-utils==3.8.1
    - pytz==2023.3.post1
    - pyyaml==6.0
    - pyzmq==25.1.2
    - referencing==0.32.0
    - regex==2022.10.31
    - requests==2.31.0
    - rpds-py==0.15.2
    - safetensors==0.4.1
    - scikit-image==0.22.0
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - semantic-version==2.10.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.99
    - sentry-sdk==1.39.1
    - setproctitle==1.3.3
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - stack-data==0.6.3
    - starlette==0.27.0
    - sympy==1.12
    - threadpoolctl==3.2.0
    - tifffile==2023.12.9
    - timm==0.6.13
    - tokenizers==0.15.0
    - toolz==0.12.0
    - torch==2.0.0
    - torchaudio==2.0.1
    - torchvision==0.15.1
    - tornado==6.4
    - tqdm==4.64.1
    - traitlets==5.14.0
    - transformers==4.36.2
    - triton==2.0.0
    - typing-extensions==4.9.0
    - tzdata==2023.3
    - urllib3==2.1.0
    - uvicorn==0.24.0.post1
    - visual-genome==1.1.1
    - wandb==0.16.1
    - wcwidth==0.2.12
    - webdataset==0.2.48
    - websockets==11.0.3
    - xxhash==3.4.1
    - yarl==1.9.4
    - zipp==3.17.0
prefix: /root/miniconda3/envs/minigptv
